apiVersion: v1
kind: Namespace
metadata:
  name: aegis-production
  labels:
    name: aegis-production
    environment: production
    compliance: soc2-compliant
    data-residency: multi-region
---
apiVersion: v1
kind: Namespace
metadata:
  name: aegis-staging
  labels:
    name: aegis-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: aegis-monitoring
  labels:
    name: aegis-monitoring
    environment: production